version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
    - cd ./pwa
    - npm install
    - npm run build:staging
    - aws s3 sync build/ s3://dev-hp-pod-ui.hyperpure.com/
